# Generated by Django 4.0.3 on 2022-03-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsletterrecipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
